In [1]:
import numpy as np

# 1. Creating Arrays
a = np.array([1, 2, 3, 4, 5])
print("1D Array:", a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

# 2. Array Properties
print("Shape:", b.shape)
print("Size:", b.size)
print("Data Type:", b.dtype)

# 3. Array Operations
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))

# 4. Zeros and Ones
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
print("Zeros:\n", zeros)
print("Ones:\n", ones)

# 5. Random Array
rand = np.random.rand(3, 3)
print("Random Array:\n", rand)

# 6. Reshaping
c = np.arange(12).reshape(3, 4)
print("Reshaped Array:\n", c)

# 7. Slicing
print("First row:", c[0])
print("Element at [1,2]:", c[1, 2])

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64
Sum: 15
Mean: 3.0
Max: 5
Min: 1
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random Array:
 [[0.20893941 0.66078457 0.82525018]
 [0.28090896 0.06172437 0.00787904]
 [0.63713379 0.78158292 0.34891563]]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
First row: [0 1 2 3]
Element at [1,2]: 6


In [2]:
# 8. Matrix Operations
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix Addition:\n", a + b)
print("Matrix Multiplication:\n", np.dot(a, b))
print("Transpose:\n", a.T)

# 9. Boolean Indexing
arr = np.array([10, 20, 30, 40, 50])
print("Elements greater than 25:", arr[arr > 25])

# 10. Statistical Operations
data = np.array([4, 7, 13, 2, 1, 8, 9, 3])
print("Sorted:", np.sort(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Elements greater than 25: [30 40 50]
Sorted: [ 1  2  3  4  7  8  9 13]
Standard Deviation: 3.822221212855164
Variance: 14.609375
